### ISSUE TITLE
contentInset issue

### ISSUE THREAD

**Issue by AndrewMagv** [lijingcheng/JCPullToRefreshView#1]
I found you set contentInset in "layoutsubviews" .
In some conditions , layoutSubView will called several times , If you put any control as subview in it.
I think it should set once when this control be initialized.

**Comment by lijingcheng** [comment]
Thank you, I add a judgment to the layoutsubviews, so contentInset assignment is just a little bit later

if (UIEdgeInsetsEqualToEdgeInsets(self.contentInset, UIEdgeInsetsMake(-1, -1, -1, -1))) {
        self.contentInset = self.scrollView.contentInset;
}
